### ISSUE TITLE
`bundle exec ruboty --dotenv` でエラー

### ISSUE THREAD

**Issue by katorie** [ikejirirb/konure#1]
```
>> bundle exec ruboty --dotenv                                                              ~/communities/ikejirirb/konure(master✗)
bundler: failed to load command: ruboty (/Users/kato/.rbenv/versions/2.2.2/bin/ruboty)
LoadError: dlopen(/Users/kato/.rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-darwin14/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /Users/kato/.rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-darwin14/readline.bundle
  Reason: image not found - /Users/kato/.rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-darwin14/readline.bundle
  /Users/kato/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruboty-1.3.0/lib/ruboty/adapters/shell.rb:1:in `require'
  /Users/kato/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruboty-1.3.0/lib/ruboty/adapters/shell.rb:1:in `<top (required)>'
  /Users/kato/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruboty-1.3.0/lib/ruboty.rb:50:in `require'
  /Users/kato/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruboty-1.3.0/lib/ruboty.rb:50:in `<top (required)>'
  /Users/kato/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruboty-1.3.0/bin/ruboty:4:in `require'
  /Users/kato/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruboty-1.3.0/bin/ruboty:4:in `<top (required)>'
  /Users/kato/.rbenv/versions/2.2.2/bin/ruboty:23:in `load'
  /Users/kato/.rbenv/versions/2.2.2/bin/ruboty:23:in `<top (required)>'
```

**Comment by katorie** [comment]
Rubyを2.4.2にしたら動いた
